/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.tulin.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class SimpleBeanAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7475844933091450408L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SimpleBeanAvro\",\"namespace\":\"com.tulin.avro\",\"fields\":[{\"name\":\"ID\",\"type\":\"int\"},{\"name\":\"Url\",\"type\":\"string\"},{\"name\":\"name\",\"type\":{\"type\":\"array\",\"items\":\"string\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SimpleBeanAvro> ENCODER =
      new BinaryMessageEncoder<SimpleBeanAvro>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SimpleBeanAvro> DECODER =
      new BinaryMessageDecoder<SimpleBeanAvro>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<SimpleBeanAvro> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<SimpleBeanAvro> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SimpleBeanAvro>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this SimpleBeanAvro to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a SimpleBeanAvro from a ByteBuffer. */
  public static SimpleBeanAvro fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int ID;
  @Deprecated public java.lang.CharSequence Url;
  @Deprecated public java.util.List<java.lang.CharSequence> name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SimpleBeanAvro() {}

  /**
   * All-args constructor.
   * @param ID The new value for ID
   * @param Url The new value for Url
   * @param name The new value for name
   */
  public SimpleBeanAvro(java.lang.Integer ID, java.lang.CharSequence Url, java.util.List<java.lang.CharSequence> name) {
    this.ID = ID;
    this.Url = Url;
    this.name = name;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ID;
    case 1: return Url;
    case 2: return name;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ID = (java.lang.Integer)value$; break;
    case 1: Url = (java.lang.CharSequence)value$; break;
    case 2: name = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'ID' field.
   * @return The value of the 'ID' field.
   */
  public java.lang.Integer getID() {
    return ID;
  }

  /**
   * Sets the value of the 'ID' field.
   * @param value the value to set.
   */
  public void setID(java.lang.Integer value) {
    this.ID = value;
  }

  /**
   * Gets the value of the 'Url' field.
   * @return The value of the 'Url' field.
   */
  public java.lang.CharSequence getUrl() {
    return Url;
  }

  /**
   * Sets the value of the 'Url' field.
   * @param value the value to set.
   */
  public void setUrl(java.lang.CharSequence value) {
    this.Url = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.util.List<java.lang.CharSequence> getName() {
    return name;
  }

  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.util.List<java.lang.CharSequence> value) {
    this.name = value;
  }

  /**
   * Creates a new SimpleBeanAvro RecordBuilder.
   * @return A new SimpleBeanAvro RecordBuilder
   */
  public static com.tulin.avro.SimpleBeanAvro.Builder newBuilder() {
    return new com.tulin.avro.SimpleBeanAvro.Builder();
  }

  /**
   * Creates a new SimpleBeanAvro RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SimpleBeanAvro RecordBuilder
   */
  public static com.tulin.avro.SimpleBeanAvro.Builder newBuilder(com.tulin.avro.SimpleBeanAvro.Builder other) {
    return new com.tulin.avro.SimpleBeanAvro.Builder(other);
  }

  /**
   * Creates a new SimpleBeanAvro RecordBuilder by copying an existing SimpleBeanAvro instance.
   * @param other The existing instance to copy.
   * @return A new SimpleBeanAvro RecordBuilder
   */
  public static com.tulin.avro.SimpleBeanAvro.Builder newBuilder(com.tulin.avro.SimpleBeanAvro other) {
    return new com.tulin.avro.SimpleBeanAvro.Builder(other);
  }

  /**
   * RecordBuilder for SimpleBeanAvro instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SimpleBeanAvro>
    implements org.apache.avro.data.RecordBuilder<SimpleBeanAvro> {

    private int ID;
    private java.lang.CharSequence Url;
    private java.util.List<java.lang.CharSequence> name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.tulin.avro.SimpleBeanAvro.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Url)) {
        this.Url = data().deepCopy(fields()[1].schema(), other.Url);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing SimpleBeanAvro instance
     * @param other The existing instance to copy.
     */
    private Builder(com.tulin.avro.SimpleBeanAvro other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.ID)) {
        this.ID = data().deepCopy(fields()[0].schema(), other.ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.Url)) {
        this.Url = data().deepCopy(fields()[1].schema(), other.Url);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'ID' field.
      * @return The value.
      */
    public java.lang.Integer getID() {
      return ID;
    }

    /**
      * Sets the value of the 'ID' field.
      * @param value The value of 'ID'.
      * @return This builder.
      */
    public com.tulin.avro.SimpleBeanAvro.Builder setID(int value) {
      validate(fields()[0], value);
      this.ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ID' field has been set.
      * @return True if the 'ID' field has been set, false otherwise.
      */
    public boolean hasID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ID' field.
      * @return This builder.
      */
    public com.tulin.avro.SimpleBeanAvro.Builder clearID() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'Url' field.
      * @return The value.
      */
    public java.lang.CharSequence getUrl() {
      return Url;
    }

    /**
      * Sets the value of the 'Url' field.
      * @param value The value of 'Url'.
      * @return This builder.
      */
    public com.tulin.avro.SimpleBeanAvro.Builder setUrl(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.Url = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'Url' field has been set.
      * @return True if the 'Url' field has been set, false otherwise.
      */
    public boolean hasUrl() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'Url' field.
      * @return This builder.
      */
    public com.tulin.avro.SimpleBeanAvro.Builder clearUrl() {
      Url = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getName() {
      return name;
    }

    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.tulin.avro.SimpleBeanAvro.Builder setName(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.tulin.avro.SimpleBeanAvro.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @SuppressWarnings("unchecked")
    public SimpleBeanAvro build() {
      try {
        SimpleBeanAvro record = new SimpleBeanAvro();
        record.ID = fieldSetFlags()[0] ? this.ID : (java.lang.Integer) defaultValue(fields()[0]);
        record.Url = fieldSetFlags()[1] ? this.Url : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SimpleBeanAvro>
    WRITER$ = (org.apache.avro.io.DatumWriter<SimpleBeanAvro>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SimpleBeanAvro>
    READER$ = (org.apache.avro.io.DatumReader<SimpleBeanAvro>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
